import { useEffect, useContext, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AuthContext } from "../store/auth-context";
import axios from "axios";

function WelcomeScreen() {
  const authCtx = useContext(AuthContext);
  const [fetchedMessage, setFetchedMessage] = useState("");

  const token = authCtx.token;
  // how to access guarded (rules) API paths using token on firebase? use "?auth=" and add the token generated by the firebase API
  useEffect(() => {
    axios
      .get(
        "https://usr-auth-default-rtdb.firebaseio.com/message.json?auth=" +
          token
      )
      .then((response) => {
        setFetchedMessage(response.data);
      });
  }, [token]);
  return (
    <View style={styles.rootContainer}>
      <Text style={styles.title}>Welcome!</Text>
      <Text>You authenticated successfully!</Text>
      <Text>{fetchedMessage}</Text>
    </View>
  );
}

export default WelcomeScreen;

const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 8,
  },
});
